name: Multiverse-Inventories
main: com.onarandombox.multiverseinventories.MultiverseInventories
version: maven-version-number
api-version: 1.13
authors: ['dumptruckman']
depend: ['Multiverse-Core']
softdepend: [MultiInv, WorldInventories, Multiverse-Adventure]

awareness:
- !@UTF8